server:
  port: 8082

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5437/database}
    username: ${SPRING_DATASOURCE_URL:postgres}
    password: ${SPRING_DATASOURCE_URL:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
